/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import PIMclass.PIMCollection;
import PIMclass.PIMEntity;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import manager.CustomizedException;

/**
 *
 * @author yangmi
 */
public class CalenderFrame extends javax.swing.JFrame {

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * Creates new form CalenderFrame
     */
    public CalenderFrame() {
        msg=new JPanel[42];
        count=0;
        date= Calendar.getInstance();
        initComponents();
        jTextField1.setText(format1.format(date.getTime()));
	pack();
    }

    public void paint(){
        this.setIfo_PIM(pimfinal.PIMFinal.getCollection());
        Calendar tem=Calendar.getInstance();
        tem.setTime(date.getTime());
        tem.set(Calendar.DAY_OF_MONTH, 1);
        int[]result=calendar.Calendarinfo.rtinf(tem);
        for(int i=0;i<42;i++){
                        msg[i].removeAll();
                        msg[i].setBackground(Color.white);
                        msg[i].updateUI();
                        if(result[i]==0)continue;
                        if(result[i]==date.get(Calendar.DAY_OF_MONTH)){
                            msg[i].setBackground(Color.red);
                        }
			msg[i].add(new JLabel(Integer.toString(result[i])),BorderLayout.SOUTH);
                        //deal with pim info
                                //不加判断的话后一句有可能会出现nullpoint error
                                if(ifo_PIM==null)continue;
                                String riqi=date.get(Calendar.YEAR)+"/"+(date.get(Calendar.MONTH)+1)+"/"+result[i];
				Date d=new Date(riqi);
                                Calendar na=Calendar.getInstance();
                                na.setTime(d);
                                Collection<PIMEntity> dat;
                                if(!jTextField2.getText().equals("")){
                                    dat=ifo_PIM.getItemsForDate(na,jTextField2.getText());
                                }
                                    else {
                                    dat=ifo_PIM.getItemsForDate(na);
                                }
				if(dat.isEmpty())continue;
				JComboBox<String> faceCombo=new JComboBox<>();
				for(Object a:dat){
					faceCombo.addItem(a.toString());
				}
				msg[i].add(faceCombo,BorderLayout.NORTH);
                                faceCombo.addActionListener(new ActionListener(){

                            @Override
                            public void actionPerformed(ActionEvent e) {
                                jTextArea1.setText(faceCombo.getItemAt(faceCombo.getSelectedIndex()));
                                jTextArea1.repaint();
                               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                            }
                                    
                                    
                                });
 
                        msg[i].updateUI();
                     
		}
        jTextArea1.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = msg[count++]=new javax.swing.JPanel();
        jPanel6 = msg[count++]=new javax.swing.JPanel();
        jPanel7 = msg[count++]=new javax.swing.JPanel();
        jPanel8 = msg[count++]=new javax.swing.JPanel();
        jPanel9 = msg[count++]=new javax.swing.JPanel();
        jPanel10 = msg[count++]=new javax.swing.JPanel();
        jPanel12 = msg[count++]=new javax.swing.JPanel();
        jPanel5 = msg[count++]=new javax.swing.JPanel();
        jPanel13 = msg[count++]=new javax.swing.JPanel();
        jPanel14 = msg[count++]=new javax.swing.JPanel();
        jPanel15 = msg[count++]=new javax.swing.JPanel();
        jPanel16 = msg[count++]=new javax.swing.JPanel();
        jPanel17 = msg[count++]=new javax.swing.JPanel();
        jPanel18 = msg[count++]=new javax.swing.JPanel();
        jPanel19 = msg[count++]=new javax.swing.JPanel();
        jPanel20 = msg[count++]=new javax.swing.JPanel();
        jPanel21 = msg[count++]=new javax.swing.JPanel();
        jPanel22 = msg[count++]=new javax.swing.JPanel();
        jPanel23 = msg[count++]=new javax.swing.JPanel();
        jPanel24 = msg[count++]=new javax.swing.JPanel();
        jPanel25 = msg[count++]=new javax.swing.JPanel();
        jPanel26 = msg[count++]=new javax.swing.JPanel();
        jPanel27 = msg[count++]=new javax.swing.JPanel();
        jPanel29 = msg[count++]=new javax.swing.JPanel();
        jPanel30 = msg[count++]=new javax.swing.JPanel();
        jPanel31 = msg[count++]=new javax.swing.JPanel();
        jPanel32 = msg[count++]=new javax.swing.JPanel();
        jPanel33 = msg[count++]=new javax.swing.JPanel();
        jPanel34 = msg[count++]=new javax.swing.JPanel();
        jPanel35 = msg[count++]=new javax.swing.JPanel();
        jPanel36 = msg[count++]=new javax.swing.JPanel();
        jPanel37 = msg[count++]=new javax.swing.JPanel();
        jPanel38 = msg[count++]=new javax.swing.JPanel();
        jPanel39 = msg[count++]=new javax.swing.JPanel();
        jPanel40 = msg[count++]=new javax.swing.JPanel();
        jPanel41 = msg[count++]=new javax.swing.JPanel();
        jPanel42 = msg[count++]=new javax.swing.JPanel();
        jPanel43 = msg[count++]=new javax.swing.JPanel();
        jPanel44 = msg[count++]=new javax.swing.JPanel();
        jPanel45 = msg[count++]=new javax.swing.JPanel();
        jPanel46 = msg[count++]=new javax.swing.JPanel();
        jPanel47 = msg[count++]=new javax.swing.JPanel();
        nextmonth = new javax.swing.JButton();
        previousmonth = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new java.awt.GridLayout(7, 7));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Su");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mo");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tu");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("We");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Th");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fr");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sa");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel10);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel12);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel5);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel18);

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel19);

        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel20);

        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel21);

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel22);

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel23);

        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel24);

        jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel25.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel25);

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel26);

        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel27);

        jPanel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel29.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel29);

        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel30);

        jPanel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel31.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel31);

        jPanel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel32.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel32);

        jPanel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel33.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel33);

        jPanel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel34.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel34);

        jPanel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel35.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel35);

        jPanel36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel36.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel36);

        jPanel37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel37.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel37);

        jPanel38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel38);

        jPanel39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel39.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel39);

        jPanel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel40.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel40);

        jPanel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel41.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel41);

        jPanel42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel42.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel42);

        jPanel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel43.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel43);

        jPanel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel44.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel44);

        jPanel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel45.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel45);

        jPanel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel46.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel46);

        jPanel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel47.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel47);

        nextmonth.setText("下个月");
        nextmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextmonthActionPerformed(evt);
            }
        });

        previousmonth.setText("上个月");
        previousmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousmonthActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("yyyy/mm/dd");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("前一天");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("后一天");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Owner：");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nextmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previousmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextmonth)
                    .addComponent(previousmonth)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        jMenu4.setText("File");

        jMenu6.setText("选择");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu6);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        jMenu1.setText("新建");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu1);
        jMenu5.add(jSeparator1);

        jMenu7.setText("查找");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu7);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextmonthActionPerformed
        // TODO add your handling code here:
        date.add(Calendar.MONTH, 1);
        jTextField1.setText(format1.format(date.getTime()));
        paint();
    }//GEN-LAST:event_nextmonthActionPerformed

    private void previousmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousmonthActionPerformed
        // TODO add your handling code here:
        date.add(Calendar.MONTH, -1);
        jTextField1.setText(format1.format(date.getTime()));
        paint();
    }//GEN-LAST:event_previousmonthActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String text;
        text=jTextField1.getText();
        Pattern pattern = Pattern.compile("^[0-9]{4}(/-|//|/.)[0-9]{0,1}(/-|//|/.)[0-9]{0,1}$");
        Matcher matcher = pattern.matcher(text);
        boolean b=matcher.matches();
        if(b==false){
            JOptionPane.showMessageDialog(nextmonth, "format erro"+text);
        }else{
            Date temp=new Date(text);
            date.setTime(temp);
            paint();
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        date.add(Calendar.DAY_OF_YEAR, -1);
        jTextField1.setText(format1.format(date.getTime()));
        paint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        date.add(Calendar.DAY_OF_YEAR, 1);
        jTextField1.setText(format1.format(date.getTime()));
        paint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        int result=chooser.showDialog(jLabel2, "select");
        if(result==JFileChooser.CANCEL_OPTION)return;
        filename=chooser.getSelectedFile().getPath();
        pimfinal.PIMFinal.getFilemanager().setFilename(filename);
        pimfinal.PIMFinal.getCollection().clear();
        ifo_PIM.clear();
        try {
            pimfinal.PIMFinal.setCollection(pimfinal.PIMFinal.getFilemanager().getAll());
        } catch (CustomizedException ex) {
            Logger.getLogger(CalenderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        paint();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        ui.editFrame edit=new ui.editFrame();
        edit.setVisible(true);
        pimfinal.PIMFinal.getFram().setEnabled(false);
        edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        ui.findFrame find =new ui.findFrame();
        find.setVisible(rootPaneCheckingEnabled);
        pimfinal.PIMFinal.getFram().setEnabled(false);
        find.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
        if(!jTextField2.getText().equals("")){
            //ifo_PIM.clear();
            ifo_PIM=pimfinal.PIMFinal.getCollection().getAllByOwner(jTextField2.getText());
        }
        else{
            ifo_PIM=pimfinal.PIMFinal.getCollection().getAll();
        }
        paint();
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalenderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalenderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalenderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalenderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalenderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton nextmonth;
    private javax.swing.JButton previousmonth;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JPanel[] msg;
    private PIMCollection ifo_PIM;

    /**
     * Get the value of ifo_PIM
     *
     * @return the value of ifo_PIM
     */
    public PIMCollection getIfo_PIM() {
        return ifo_PIM;
    }

    /**
     * Set the value of ifo_PIM
     *
     * @param ifo_PIM new value of ifo_PIM
     */
    public void setIfo_PIM(PIMCollection ifo_PIM) {
        this.ifo_PIM = ifo_PIM;
    }

    private String filename;

    /**
     * Get the value of filename
     *
     * @return the value of filename
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Set the value of filename
     *
     * @param filename new value of filename
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    private Calendar date;
    DateFormat format1 = new SimpleDateFormat("yyyy/MM/dd");
    /**
     * Get the value of date
     *
     * @return the value of date
     */
    public Calendar getDate() {
        return date;
    }

    /**
     * Set the value of date
     *
     * @param date new value of date
     */
    public void setDate(Calendar date) {
        this.date = date;
    }

    private static int count = 0;
    
    /**
     * Get the value of msg
     *
     * @return the value of msg
     */
    public javax.swing.JPanel[] getMsg() {
        return msg;
    }

    /**
     * Set the value of msg
     *
     * @param msg new value of msg
     */
    public void setMsg(javax.swing.JPanel[] msg) {
        this.msg = msg;
    }

    /**
     * Get the value of msg at specified index
     *
     * @param index the index of msg
     * @return the value of msg at specified index
     */
    public javax.swing.JPanel getMsg(int index) {
        return this.msg[index];
    }

    /**
     * Set the value of msg at specified index.
     *
     * @param index the index of msg
     * @param msg new value of msg at specified index
     */
    public void setMsg(int index, javax.swing.JPanel msg) {
        this.msg[index] = msg;
    }
}
